In [1]:
# Q1
import numpy as np
array_ones = np.ones((2, 3))
array_zeros = np.zeros((3, 3))
array_sevens = np.full((2, 5), 7)
print("2-by-3 array with ones:")
print(array_ones)

print("\n3-by-3 array with zeros:")
print(array_zeros)

print("\n2-by-5 array with sevens:")
print(array_sevens)

2-by-3 array with ones:
[[1. 1. 1.]
 [1. 1. 1.]]

3-by-3 array with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2-by-5 array with sevens:
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [2]:
#2
import numpy as np

array = np.arange(4).reshape(2, 2)

cubed_array = array ** 3
added_array = array + 7
multiplied_array = array * 2

print(cubed_array)
print(added_array)
print(multiplied_array)


[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [3]:
import numpy as np

array1 = np.arange(2, 19, 2).reshape(3, 3)
array2 = np.arange(9, 0, -1).reshape(3, 3)
result = array1 * array2

print(result)


[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [4]:
import numpy as np

array = np.arange(12).reshape(3, 4)
swapped_array = array[[1, 0, 2], :][:, [2, 3, 0, 1]]

print(swapped_array)


[[ 6  7  4  5]
 [ 2  3  0  1]
 [10 11  8  9]]


In [5]:
import numpy as np

array = np.array([[2, 3, 5, 7, 11], [13, 17, 19, 23, 29]])

print(array)


[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [6]:
import numpy as np
arr = np.array([2**i for i in range(6)]).reshape(2, 3)
flattened = arr.flatten()
print("Flattened array:", flattened)
raveled = arr.ravel()
print("Raveled array:", raveled)
print("Original array after flatten and ravel:", arr)


Flattened array: [ 1  2  4  8 16 32]
Raveled array: [ 1  2  4  8 16 32]
Original array after flatten and ravel: [[ 1  2  4]
 [ 8 16 32]]


In [7]:
from collections import Counter
import numpy as np

arr = [6, 9, 5, 1, 7, 5, 10, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 1, 1, 9, 5, 3, 8, 7, 9, 6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6]
counts = Counter(arr)
most_frequent = counts.most_common()
print("Most frequent values:", most_frequent)


Most frequent values: [(5, 7), (7, 6), (9, 5), (6, 4), (1, 4), (0, 4), (2, 3), (8, 2), (3, 2), (10, 1), (4, 1)]


In [8]:
import numpy as np

arr = np.linspace(1.1, 6.6, 6).reshape(2, 3)
arr = arr.astype(int)
print(arr)


[[1 2 3]
 [4 5 6]]


In [9]:
def format_2d_array(arr):
    max_width = max(len(str(num)) for row in arr for num in row)
    return '\n'.join(' '.join(f"{num:>{max_width}}" for num in row) for row in arr)

arr = [[1, 23, 456], [7890, 12, 3]]
print(format_2d_array(arr))


   1   23  456
7890   12    3


In [10]:
import numpy as np

arr = np.arange(1, 16).reshape(3, 5)

print("Row 2:", arr[1])
print("Column 5:", arr[:, 4])
print("Rows 0 and 1:", arr[0:2])
print("Columns 2–4:", arr[:, 2:5])
print("Element at row 1 and column 4:", arr[1, 3])
print("Elements from rows 1 and 2 in columns 0, 2, and 4:", arr[1:3][:, [0, 2, 4]])


Row 2: [ 6  7  8  9 10]
Column 5: [ 5 10 15]
Rows 0 and 1: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Columns 2–4: [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
Element at row 1 and column 4: 9
Elements from rows 1 and 2 in columns 0, 2, and 4: [[ 6  8 10]
 [11 13 15]]


In [13]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

array3 = np.vstack((array1, array2))
print("Vertical stacking (array3):\n", array3)

array4 = np.hstack((array1, array2))
print("Horizontal stacking (array4):\n", array4)

array5 = np.vstack((array3, array3))  # Stack array3 twice vertically
print("Vertical stacking copies (array5):\n", array5)

array6 = np.hstack((array4, array4))  # Stack array4 twice horizontally
print("Horizontal stacking copies (array6):\n", array6)


Vertical stacking (array3):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Horizontal stacking (array4):
 [[0 1 4 5]
 [2 3 6 7]]
Vertical stacking copies (array5):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
Horizontal stacking copies (array6):
 [[0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]]


In [16]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# Vertical stacking using concatenate (axis=0)
array3 = np.concatenate((array1, array2), axis=0)
print("Vertical stacking (array3):\n", array3)

# Horizontal stacking using concatenate (axis=1)
array4 = np.concatenate((array1, array2), axis=1)
print("Horizontal stacking (array4):\n", array4)

# Vertical stacking copies of array3
array5 = np.concatenate((array3, array3), axis=0)
print("Vertical stacking copies (array5):\n", array5)

# Horizontal stacking copies of array4
array6 = np.concatenate((array4, array4), axis=1)
print("Horizontal stacking copies (array6):\n", array6)


Vertical stacking (array3):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Horizontal stacking (array4):
 [[0 1 4 5]
 [2 3 6 7]]
Vertical stacking copies (array5):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
Horizontal stacking copies (array6):
 [[0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]]


In [18]:
import numpy as np

array = np.full((8, 8), '*', dtype=str)
array[1::2, ::2] = '-'
array[::2, 1::2] = '-'

print("Checkerboard pattern of dashes and asterisks:\n", array)


Checkerboard pattern of dashes and asterisks:
 [['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']]


In [19]:
import numpy as np

array = np.random.randint(0, 100, (5, 5))
count = np.sum((array >= 0) & (array <= 99))

print("Array:\n", array)
print("Count of elements between 0 and 99:", count)


Array:
 [[19 10 91 31 54]
 [65 93 80 54 93]
 [62 99 41  8 90]
 [90 93 59 91  9]
 [ 3 31 37 32 17]]
Count of elements between 0 and 99: 25


In [21]:
import numpy as np
from collections import Counter

def median_and_mode(array):
    median = np.median(array)
    flat_array = array.flatten()
    mode = Counter(flat_array).most_common(1)[0][0]
    return median, mode

array1 = np.random.randint(0, 100, (3, 3))
array2 = np.random.randint(0, 100, (2, 5))
array3 = np.random.randint(0, 100, (4, 4))

for i, array in enumerate([array1, array2, array3], 1):
    median, mode = median_and_mode(array)
    print(f"Array {i}:\n{array}\nMedian: {median}, Mode: {mode}\n")


Array 1:
[[18 14 16]
 [41 64 73]
 [41  9  2]]
Median: 18.0, Mode: 41

Array 2:
[[49 49 26 67 86]
 [52 50 17 19 36]]
Median: 49.0, Mode: 49

Array 3:
[[14 37 37 98]
 [94 59 81 58]
 [ 1 80 53 79]
 [93 64 42 47]]
Median: 58.5, Mode: 37



In [26]:
import numpy as np

array = np.random.randint(0, 100, (9, 9, 2))
extracted_array = array[5, 5, 1]

print("Original 9*9*2 Array:\n", array)
print("Extracted value at (5,5,2):", extracted_array)


Original 9*9*2 Array:
 [[[53 94]
  [90 63]
  [86 97]
  [59  2]
  [39 15]
  [43 13]
  [44 56]
  [63  3]
  [29 76]]

 [[36 74]
  [14 95]
  [ 8 76]
  [82 88]
  [91 61]
  [10 24]
  [30 37]
  [ 3 44]
  [38 41]]

 [[80 39]
  [41 91]
  [11 11]
  [51 96]
  [36 28]
  [47 68]
  [86 38]
  [66 37]
  [60 86]]

 [[87  7]
  [82 15]
  [60 10]
  [50 48]
  [81 60]
  [14 55]
  [ 8 86]
  [75 98]
  [34 72]]

 [[44 20]
  [47 95]
  [27  6]
  [ 0 74]
  [89 77]
  [29 89]
  [68 76]
  [ 1 60]
  [45 70]]

 [[21 32]
  [28 50]
  [93 39]
  [40 57]
  [29 54]
  [64 95]
  [79 80]
  [ 1 16]
  [83 32]]

 [[49 59]
  [17  8]
  [57 95]
  [19 93]
  [36 10]
  [82 94]
  [43 84]
  [49 77]
  [28 79]]

 [[83 42]
  [64 96]
  [77 10]
  [42 40]
  [66 89]
  [79 24]
  [56 21]
  [96 63]
  [85 64]]

 [[18  6]
  [19 92]
  [29 81]
  [15 78]
  [28  9]
  [39 80]
  [43  6]
  [70 42]
  [28 75]]]
Extracted value at (5,5,2): 95


In [27]:
import numpy as np

# Create a 4x4 array with random values
array = np.random.rand(4, 4)

# Sort each column
array_sorted = np.sort(array, axis=0)

# Display the original and sorted array
print("Original Array:\n", array)
print("Sorted Array (by column):\n", array_sorted)


Original Array:
 [[0.55016714 0.59953452 0.533178   0.8393219 ]
 [0.01988329 0.18658618 0.91320407 0.92563372]
 [0.2495077  0.6205814  0.51176974 0.31148995]
 [0.43646032 0.77581264 0.37880992 0.94354993]]
Sorted Array (by column):
 [[0.01988329 0.18658618 0.37880992 0.31148995]
 [0.2495077  0.59953452 0.51176974 0.8393219 ]
 [0.43646032 0.6205814  0.533178   0.92563372]
 [0.55016714 0.77581264 0.91320407 0.94354993]]


In [28]:
import pandas as pd

# Example DataFrame
data = {
    'Column1': [10, 20, 30],
    'Column2': [40, 50, 60]
}
df = pd.DataFrame(data)

# Convert the first column of the DataFrame to a Series
first_column_series = df.iloc[:, 0]

# Display the resulting Series
print("First column as a Series:\n", first_column_series)


First column as a Series:
 0    10
1    20
2    30
Name: Column1, dtype: int64


In [30]:
import pandas as pd

# Create two Series objects
s1 = pd.Series([1, 2, 3, 4, 2])
s2 = pd.Series([3, 4, 5, 6])

# Find elements in s1 that are not in s2
result = s1[~s1.isin(s2)]

# Display the result
print("Elements in s1 not present in s2:\n", result)


Elements in s1 not present in s2:
 0    1
1    2
4    2
dtype: int64


In [31]:
import pandas as pd

# Input series
s = pd.Series([1, 1, 3, 7, 88, 12, 88, 23, 3, 1, 9, 0])

# Find the index of the first occurrence of the smallest and largest value
smallest_index = s.idxmin()
largest_index = s.idxmax()

# Display the results
print("Index of the first occurrence of the smallest value:", smallest_index)
print("Index of the first occurrence of the largest value:", largest_index)


Index of the first occurrence of the smallest value: 11
Index of the first occurrence of the largest value: 4


In [29]:
import pandas as pd

# Create the Series
L = ['Cry', 'Apple', 'Orange', 'Sky', 'Banana']
series = pd.Series(L)

# Create a new series with elements that contain a vowel
series_with_vowel = series[series.str.contains(r'[AEIOUaeiou]', regex=True)]

# Create another series with elements that start with a vowel
series_start_with_vowel = series[series.str.contains(r'^[AEIOUaeiou]', regex=True)]

# Display the results
print("Original Series:\n", series)
print("\nSeries with elements containing a vowel:\n", series_with_vowel)
print("\nSeries with elements starting with a vowel:\n", series_start_with_vowel)


Original Series:
 0       Cry
1     Apple
2    Orange
3       Sky
4    Banana
dtype: object

Series with elements containing a vowel:
 1     Apple
2    Orange
4    Banana
dtype: object

Series with elements starting with a vowel:
 1     Apple
2    Orange
dtype: object


In [32]:
import pandas as pd

# (a) Create a Series from the list [7, 11, 13, 17]
series_a = pd.Series([7, 11, 13, 17])
print("(a) Series:\n", series_a)

# (b) Create a Series with five elements where each element is 100.0
series_b = pd.Series([100.0] * 5)
print("\n(b) Series:\n", series_b)

# (c) Create a Series with 20 elements that are random numbers in the range 0 to 100
import numpy as np
series_c = pd.Series(np.random.randint(0, 101, 20))
print("\n(c) Series:\n", series_c)
print("\nDescriptive Statistics:\n", series_c.describe())

# (d) Create a Series called `temperatures` with floating-point values and custom indices
temperatures = pd.Series(
    [98.6, 98.9, 100.2, 97.9],
    index=['Julie', 'Charlie', 'Sam', 'Andrea']
)
print("\n(d) Temperatures Series:\n", temperatures)

# (e) Form a dictionary from names and values in Part (d), then use it to initialize a Series
temp_dict = temperatures.to_dict()
series_e = pd.Series(temp_dict)
print("\n(e) Series initialized from dictionary:\n", series_e)


(a) Series:
 0     7
1    11
2    13
3    17
dtype: int64

(b) Series:
 0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64

(c) Series:
 0     79
1     61
2     10
3     52
4     55
5     31
6     73
7     36
8     38
9     24
10    54
11    37
12    11
13    92
14    88
15    22
16    13
17    78
18    82
19    46
dtype: int32

Descriptive Statistics:
 count    20.000000
mean     49.100000
std      26.528832
min      10.000000
25%      29.250000
50%      49.000000
75%      74.250000
max      92.000000
dtype: float64

(d) Temperatures Series:
 Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64

(e) Series initialized from dictionary:
 Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64


In [ ]:
import pandas as pd

# (a) Create a DataFrame named `temperatures` from a dictionary
data = {
    'Maxine': [98.6, 99.1, 100.2],
    'James': [97.4, 98.3, 99.7],
    'Amanda': [99.0, 98.8, 100.1]
}
temperatures = pd.DataFrame(data, index=['Morning', 'Afternoon', 'Evening'])
print("(a) DataFrame:\n", temperatures)

# (b) Recreate the DataFrame `temperatures` using `index` keyword argument
temperatures_recreated = pd.DataFrame(
    data,
    index=['Morning', 'Afternoon', 'Evening']
)
print("\n(b) Recreated DataFrame:\n", temperatures_recreated)

# (c) Select the column of temperature readings for 'Maxine'
maxine_column = temperatures['Maxine']
print("\n(c) Column of temperature readings for 'Maxine':\n", maxine_column)

# (d) Select the row of 'Morning' temperature readings
morning_row = temperatures.loc['Morning']
print("\n(d) Row of 'Morning' temperature readings:\n", morning_row)

# (e) Select the rows for 'Morning' and 'Evening' temperature readings
morning_evening_rows = temperatures.loc[['Morning', 'Evening']]
print("\n(e) Rows for 'Morning' and 'Evening' temperature readings:\n", morning_evening_rows)

# (f) Select the columns of temperature readings for 'Amanda' and 'Maxine'
amanda_maxine_columns = temperatures[['Amanda', 'Maxine']]
print("\n(f) Columns of temperature readings for 'Amanda' and 'Maxine':\n", amanda_maxine_columns)

# (g) Select the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Afternoon'
subset = temperatures.loc[['Morning', 'Afternoon'], ['Amanda', 'Maxine']]
print("\n(g) Elements for 'Amanda' and 'Maxine' in 'Morning' and 'Afternoon':\n", subset)

# (h) Use the `describe` method to produce the DataFrame's descriptive statistics
descriptive_stats = temperatures.describe()
print("\n(h) Descriptive Statistics:\n", descriptive_stats)

# (i) Sort the temperatures DataFrame so that its columns are in alphabetical order
sorted_temperatures = temperatures.sort_index(axis=1)
print("\n(i) DataFrame with columns sorted alphabetically:\n", sorted_temperatures)


(a) DataFrame:
            Maxine  James  Amanda
Morning      98.6   97.4    99.0
Afternoon    99.1   98.3    98.8
Evening     100.2   99.7   100.1

(b) Recreated DataFrame:
            Maxine  James  Amanda
Morning      98.6   97.4    99.0
Afternoon    99.1   98.3    98.8
Evening     100.2   99.7   100.1

(c) Column of temperature readings for 'Maxine':
 Morning       98.6
Afternoon     99.1
Evening      100.2
Name: Maxine, dtype: float64

(d) Row of 'Morning' temperature readings:
 Maxine    98.6
James     97.4
Amanda    99.0
Name: Morning, dtype: float64

(e) Rows for 'Morning' and 'Evening' temperature readings:
          Maxine  James  Amanda
Morning    98.6   97.4    99.0
Evening   100.2   99.7   100.1

(f) Columns of temperature readings for 'Amanda' and 'Maxine':
            Amanda  Maxine
Morning      99.0    98.6
Afternoon    98.8    99.1
Evening     100.1   100.2

(g) Elements for 'Amanda' and 'Maxine' in 'Morning' and 'Afternoon':
            Amanda  Maxine
Morning      99.

: 