In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a.view()
b[0] = 100
print(a)
print(b)
print(a is b)

[100   2   3   4]
[100   2   3   4]
False


In [2]:
# Reshape() :-
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = a.reshape(2,6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [3]:
# Transpose :-
print(a.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [4]:
# pandas
import pandas as pd
data = {'Name' : ['Alice','Bob','Charlie'],'Age' : [10,15,20], 'City' : ['CTC','BBS','BHM']}
df = pd.DataFrame(data)
print(df)

      Name  Age City
0    Alice   10  CTC
1      Bob   15  BBS
2  Charlie   20  BHM


In [7]:
# operations
print(df['Age']) #print column age

0    10
1    15
2    20
Name: Age, dtype: int64


In [8]:
print(df.iloc(0)) #location

In [20]:
df['Mark'] = [10,20,30] #add mark
df.loc[1:3,['Name', 'Age']] #print row 1 to 3 of column name and age

Name  Age
1      Bob   15
2  Charlie   20
3      abc   25

In [15]:
df.loc[len(df)] = ['abc',25,'efg',20] #add new row
df.drop('Age',axis = 1) #Delete column 1 (Age)

Name City  Mark
0    Alice  CTC    10
1      Bob  BBS    20
2  Charlie  BHM    30
3      abc  efg    20
4      abc  efg    20

In [14]:
df.drop(1,axis = 0) #Delete row 1 (Bob)

Name  Age City  Mark
0    Alice   10  CTC    10
2  Charlie   20  BHM    30
3      abc   25  efg    20
4      abc   25  efg    20

In [35]:
# Strings
s1 = "     Good     "
s1.strip()

'Good'

In [38]:
s1.lstrip()

'Good     '

In [39]:
s1.rstrip()

'     Good'

In [36]:
s2 = "Good morning"
s2.capitalize()

'Good morning'

In [37]:
s3 = "good morning"
s3.title()

'Good Morning'

In [27]:
s1 = "orange"
s2 = "Orange"
print(s1 < s2)

False


In [40]:
s4 = "to be or not to be"
s4.count('to')

2

In [41]:
s4.rindex('to')

13

In [43]:
print('be' in s4)
s4.startswith('to')

True


True

In [44]:
s4.replace('to','go')

'go be or not go be'

In [46]:
s5 = 'a,b,c,d'
s5.split(',') #splitting

['a', 'b', 'c', 'd']

In [47]:
list1 = ['a','b','c','d']
','.join(list1) #joining

'a,b,c,d'

In [48]:
s5 = 'good morning'
s5.split(',') #splitting

['good morning']

In [49]:
list1 = ['good','morning']
','.join(list1) #joining

'good,morning'

In [58]:
' '.join(list1[::-1])

'morning good'

In [59]:
# Q1. Reverse words in a sentence
string = "Hello my name is Aditya Prasad Sahu"
' '.join(string.split(" ")[::-1])

'Sahu Prasad Aditya is name my Hello'

In [54]:
# Q2. Check for anagrams(silent, listen)

In [64]:
# Q3. Find frequency of each charecter
frequency = {}
for char in string: frequency[char] = frequency.get(char,0) +1
print(frequency)

{'H': 1, 'e': 2, 'l': 2, 'o': 1, ' ': 6, 'm': 2, 'y': 2, 'n': 1, 'a': 5, 'i': 2, 's': 2, 'A': 1, 'd': 2, 't': 1, 'P': 1, 'r': 1, 'S': 1, 'h': 1, 'u': 1}


In [65]:
# Q4. Check for substring
print("Aditya" in string)

True


In [70]:
# Q5. Count vowels and consonants
consonants, vowels = 0,0
for char in string:
    if char in "aeiou": vowels += 1
    elif char == " ": continue
    else: consonants += 1
print("Vowels :",vowels,"\nConsonants :",consonants)

Vowels : 11 
Consonants : 18


In [78]:
# Q6. Find most frequent character
count = 0
for key in frequency:
    if frequency[key] > count: 
        maxkey = key
        count = frequency[key]
print("Character :",maxkey,"\nCount :",count)

Character :  
